[package]
name = "cpu-usage-service"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
wit-bindgen = "0.46.0"
sysinfo = "0.37.2"
tokio = { version = "1", default-features = false, features = ["sync", "macros", "io-util", "rt", "time"] }
