operator:
  image:
    tag: canary

gateway:
  enabled: true
  image:
    registry: ttl.sh
    repository: lxfontes/runtime-gateway
    tag: canary
  service:
    type: NodePort
    nodePort: 30950

runtime:
  image:
    tag: canary-v2
  hostGroups:
    - name: default
      replicas: 3
      service:
        type: ClusterIP
      webgpu:
        enabled: true
      http:
        enabled: true
        port: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m" # 0.25 CPU cores
        limits:
          memory: "512Mi"
          cpu: "500m" # 0.5 CPU cores