version: 2.0.0-rc.7

build:
  command: cargo build --workspace --target wasm32-wasip2 --release
  component_path: target/wasm32-wasip2/release/http_api.wasm

dev:
  components:
    - name: task-one
      file: target/wasm32-wasip2/release/task_one.wasm
