{{- if .Values.runtime.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "runtime-operator.serviceAccountName" . }}-runtime
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime-operator.labels" . | nindent 4 }}
  {{- with .Values.runtime.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
