name = "app-test-component"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wasm_target = "wasm32-wasip2"

[[registry.pull.sources]]
target = "example:create/create"
source = "file://../mock-create-component/wit/world.wit"

[[registry.pull.sources]]
target = "example:update/update"
source = "file://../mock-update-component/wit/world.wit"
