# This rule is not used by the project ru itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over runtime.wasmcloud.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ru
    app.kubernetes.io/managed-by: kustomize
  name: runtime-host-admin-role
rules:
- apiGroups:
  - runtime.wasmcloud.dev
  resources:
  - hosts
  verbs:
  - '*'
- apiGroups:
  - runtime.wasmcloud.dev
  resources:
  - hosts/status
  verbs:
  - get
