# This rule is not used by the project ru itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to runtime.wasmcloud.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ru
    app.kubernetes.io/managed-by: kustomize
  name: runtime-host-viewer-role
rules:
- apiGroups:
  - runtime.wasmcloud.dev
  resources:
  - hosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - runtime.wasmcloud.dev
  resources:
  - hosts/status
  verbs:
  - get
