apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: {{ .Release.Namespace }}
  labels:
    wasmcloud.com/name: nats
    {{- include "runtime-operator.labels" . | nindent 4 }}
spec:
  selector:
    wasmcloud.com/name: nats
  type: ClusterIP
  ports: 
    - port: 4222
      targetPort: nats
      protocol: TCP
      name: nats