{{- if and .Values.nats.enabled .Values.nats.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nats.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime-operator.labels" . | nindent 4 }}
  {{- with .Values.nats.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
