apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: cron
spec:
  replicas: 1
  template:
    spec:
      hostSelector:
        hostgroup: default
      components:
        - name: stateless
          image: <from https://github.com/wasmCloud/wash/tree/main/examples/cron-component>
      service:
        image: <from https://github.com/wasmCloud/wash/tree/main/examples/cron-service>
