{{- $registry := .Values.runtime.image.registry | default .Values.global.image.registry | default "docker.io" -}}
{{- $top := . }}
{{- range .Values.runtime.hostGroups }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostgroup-{{ .name }}
  namespace: {{ $top.Release.Namespace }}
  labels:
    wasmcloud.com/name: hostgroup
    wasmcloud.com/hostgroup: {{ .name }}
    {{- include "runtime-operator.labels" $top | nindent 4 }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      wasmcloud.com/name: hostgroup
      wasmcloud.com/hostgroup: {{ .name }}
  template:
    metadata:
      labels:
        wasmcloud.com/name: hostgroup
        wasmcloud.com/hostgroup: {{ .name }}
        {{- include "runtime-operator.labels" $top | nindent 8 }}
    spec:
      volumes:
        - name: runtime-cert
          secret:
            secretName: {{ $top.Values.global.certificates.runtimeCertSecretName }}
        - name: data-cert
          secret:
            secretName: {{ $top.Values.global.certificates.dataCertSecretName }}
            # update this
      serviceAccountName: {{ include "runtime.serviceAccountName" $top }}
      {{- include "runtime-operator.imagePullSecrets" $top | nindent 6 }}
      containers:
        - name: host
          image: {{ printf "%s/%s" $registry $top.Values.runtime.image.repository }}:{{ $top.Values.runtime.image.tag | default $top.Chart.AppVersion }}
          env:
            - name: WASMCLOUD_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - "host"
            - "--host-name=$(WASMCLOUD_HOST_IP)"
            - "--host-group={{ .name }}"
            - "--scheduler-nats-url=nats://nats:4222"
            - "--scheduler-nats-tls-ca=/runtime-cert/ca.crt"
            - "--scheduler-nats-tls-cert=/runtime-cert/tls.crt"
            - "--scheduler-nats-tls-key=/runtime-cert/tls.key"
            - "--data-nats-url=nats://nats:4222"
            - "--data-nats-tls-ca=/data-cert/ca.crt"
            - "--data-nats-tls-cert=/data-cert/tls.crt"
            - "--data-nats-tls-key=/data-cert/tls.key"
            {{- if and (.http) (.http.enabled) }}
            - "--http-addr=0.0.0.0:9191"
            {{- end }}
            {{- if and (.webgpu) (.webgpu.enabled) }}
            - "--wasi-webgpu"
            {{- end }}
          imagePullPolicy: {{ $top.Values.runtime.image.pull_policy }}
          volumeMounts:
            - name: runtime-cert
              mountPath: /runtime-cert
              readOnly: true
            - name: data-cert
              mountPath: /data-cert
              readOnly: true
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- if and (.http) (.http.enabled) }}
            - name: http
              containerPort: 9191
              protocol: TCP
            {{- end }}
          securityContext:
            capabilities:
              drop:
                - NET_RAW
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
---
{{- end }}
