{{- if and .Values.operator.serviceAccount.create .Values.operator.watchNamespaces -}}
{{- range .Values.operator.watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "runtime-operator.fullname" $ }}-{{ . }}
  namespace: {{ . }}
  labels:
    {{- include "runtime-operator.labels" $ | nindent 4 }}
  annotations: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "runtime-operator.fullname" $ }}-{{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "runtime-operator.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
