build:
  command: cargo build --target wasm32-wasip2 --release
  component_path: target/wasm32-wasip2/release/http_counter.wasm

dev:
  wasi_blobstore_path: tmp/blobstore
  wasi_keyvalue_path: tmp/keyvalue
