name = "http-test-component"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wasm_target = "wasm32-wasip2"

[[registry.pull.sources]]
target = "example:action/action"
source = "file://../app-test-component/wit/world.wit"
