build:
  command: cargo build --target wasm32-wasip2 --release
  component_path: target/wasm32-wasip2/release/cron-service.wasm

dev:
  # We are developing a service, so tell Wash to treat it as such.
  service: true
  # Loads a sample cron task
  components:
    - name: cron-component
      file: ../cron-component/target/wasm32-wasip2/release/cron_component.wasm
