build:
  rust:
    target: wasm32-wasip2
    release: true

dev:
  # We are developing a service, so tell Wash to treat it as such.
  service: true
  # Loads a sample cron task
  components:
    - ../cron-component/target/wasm32-wasip2/release/cron_component.wasm
