build:
  command: cargo build --target wasm32-wasip2 --release
  component_path: target/wasm32-wasip2/release/cron_component.wasm

dev:
  # bind to another port so it doesnt collide with cron-service dev
  address: 0.0.0.0:8001
  # We need a service to call the cron component.
  service_file: ../cron-service/target/wasm32-wasip2/release/cron-service.wasm
