{{- if .Values.operator.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "runtime-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime-operator.labels" . | nindent 4 }}
  annotations: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "runtime-operator.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "runtime-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
