{{- if .Values.gateway.enabled -}}
{{- $registry := .Values.gateway.image.registry | default .Values.global.image.registry | default "docker.io" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runtime-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    wasmcloud.com/name: runtime-gateway
    {{- include "runtime-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      wasmcloud.com/name: runtime-gateway
  template:
    metadata:
      labels:
        wasmcloud.com/name: runtime-gateway
        {{- include "runtime-operator.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "runtime-operator.serviceAccountName" . }}-gateway
      {{- include "runtime-operator.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: runtime-operator
          image: {{ printf "%s/%s" $registry .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag | default .Chart.AppVersion }}
          args:
            - "-bind-addr=0.0.0.0:8000"
            {{- with .Values.gateway.fallbackEndpoint }}
            - "-fallback-endpoint={{ . }}"
            {{- end }}
          imagePullPolicy: {{ .Values.gateway.image.pull_policy }}
          ports:
            - name: http
              containerPort: 8000
          securityContext:
            capabilities:
              drop:
                - NET_RAW
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
{{- end }}