{{- if .Values.gateway.enabled -}}
{{- if .Values.gateway.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "runtime-operator.serviceAccountName" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime-operator.labels" . | nindent 4 }}
  {{- with .Values.gateway.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
