{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: runtime-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    wasmcloud.com/name: runtime-gateway
    {{- include "runtime-operator.labels" . | nindent 4 }}
spec:
  selector:
    wasmcloud.com/name: runtime-gateway
  type: {{ .Values.gateway.service.type }}
  ports: 
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- with .Values.gateway.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
{{- end }}