[package]
name = "qrcode"
edition = "2024"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wstd = "0.6.3"
qrcode = "0.14.1"
image = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"