version: 2.0.0-rc.5

build:
  command: cargo build --target wasm32-wasip2 --release
  component_path: target/wasm32-wasip2/release/inter_component_call_caller.wasm

dev:
  components:
    - name: callee
      file: ../inter-component-call-callee/target/wasm32-wasip2/release/inter_component_call_callee.wasm
