[package]
name = "http-api"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { workspace = true }
wstd = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }