name: docker-build-push
on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: false
        default: "."
      file:
        type: string
        required: false
        description: "Dockerfile to use for the build. Defaults to Dockerfile in the working directory"
        default: "./Dockerfile"
      image:
        type: string
        required: true
        description: "Image to use for the build WITHOUT the tag"
      tags:
        type: string
        required: true
        description: "Tags to use for the image. Follows the format of docker/metadata-action@v5"
      build-args:
        type: string
        required: false
        description: "Build arguments to pass to docker build"
        default: ""
      push:
        type: boolean
        description: "Build and Push Image. Default=false"
        required: false
        default: false
      build-contexts:
        type: string
        required: false
        description: "Additional build contexts"
      build-cache:
        type: boolean
        required: false
        description: "Enables Github Actions Image cache. Default=true"
        default: true
    outputs:
      image_digest:
        description: "Image digest of the container that was built"
        value: ${{ jobs.build.outputs.image_digest }}
      artifact_prefix:
        description: "Image digest of the container that was built without the sha256: prefix"
        value: ${{ jobs.build.outputs.artifact_prefix }}

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    permissions:
      contents: write
      packages: write
    outputs:
      image_digest: ${{ steps.build.outputs.digest }}
      artifact_prefix: ${{ steps.meta.outputs.artifact_prefix }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Login to ghcr.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ricochet
          password: ${{ secrets.WASMCLOUD_PACKAGES_PAT }}
          # username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta
        id: meta
        run: |
          # Create a prefix for the artifact name by taking the image name, removing any registry and replacing / and : with _
          ARTIFACT_PREFIX=$(echo "${{ inputs.image }}" | sed 's/.*\///; s/[\/:]/_/g')
          echo "artifact_prefix=${ARTIFACT_PREFIX}" >> "${GITHUB_OUTPUT}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          file: ${{ inputs.file }}
          context: ${{ inputs.working-directory }}
          tags: ${{ inputs.image }}
          build-contexts: ${{ inputs.build-contexts }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          build-args: ${{ inputs.build-args }}
          cache-from: |
            type=gha,scope=buildx-${{ steps.meta.outputs.artifact_prefix }}-${{ matrix.arch }}-${{ github.ref_name }}
            type=gha,scope=buildx-${{ steps.meta.outputs.artifact_prefix }}-${{ matrix.arch }}-main
          cache-to: |
            type=gha,scope=buildx-${{ steps.meta.outputs.artifact_prefix }}-${{ matrix.arch }}-${{ github.ref_name }},mode=max

      - name: Export digest
        id: export
        run: | #shell
          mkdir -p "${{ runner.temp }}/digests"
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: digests-${{ steps.meta.outputs.artifact_prefix }}-${{ github.run_id }}-linux-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    if: ${{ inputs.push }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - build
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Download digests
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-${{ needs.build.outputs.artifact_prefix }}-${{ github.run_id }}-*
          merge-multiple: true

      - name: Login to ghcr.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ricochet
          password: ${{ secrets.WASMCLOUD_PACKAGES_PAT }}
          # username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
          tags: ${{ inputs.tags }}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          # shellcheck disable=SC2046
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ inputs.image }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ inputs.image }}:${{ steps.meta.outputs.version }}
